# Site settings
title: Garlapati Bujimalla
description: Credit Information Data with Data Visualization
baseurl: "/Garlapati_AIT580"
url: "https://vrgarlapati.github.io/" # the base hostname & protocol for your site.

# Banner Section
hero: 112.jpg
hero-title: Welcome to Garlapati Bujimalla
hero-description: Analysis on Consumer complaints Database.

# Author - Creator
author-name: Videesh Reddy Garlapati
author-image:
about-author: My name is Videeh. Student at GMU.
author-email: vgarlapa@gmu.edu


# Other Authors - here you can add Other authors.
authors:
  Neehar Bujimalla:
    author-name: Neehar Bujimalla
    author-image: 
    about-author: My name is Neehar Bujimalla.
    author-email: vbujimal@gmu.edu


# Contact Form Settings
contact-subtitle: Contact us if you have any doubts # Title for the subscription form.

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
