# Site settings
title: Garlapati Bujimalla
description: Credit Information Data with Data Visulation by VIDEESH REDDY GARLAPATI, NEEHAR BUJIMALLA
baseurl: "/Garlapati_AIT580" # the subpath of your site, e.g. /blog
url: "https://vrgarlapati.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner Section
hero: 112.jpg
hero-title: Wlcome to Garlapati Bujimalla
hero-description: Credit Information Data with Data Visulation.

# Author - Creator
author-name: Videesh Reddy Garlapati
author-image: 10.jpg
about-author: My name is Videeh. Student at GMU.
author-email: help.example@gmail.com
author-twitter: https://twitter.com/
author-facebook: https://twitter.com/
author-instagram: https://www.instagram.com/
author-pinterest: https://pinterest.com/

# Other Authors - here you can add Other authors.
authors:
  Neehar Bujimalla:
    author-name: Neehar Bujimalla
    author-image: 111.jpg
    about-author: My name is Neehar Bujimalla.
    author-email: example@gmail.com
    author-twitter: https://twitter.com/
    author-facebook: https://twitter.com/
    author-instagram: https://www.instagram.com/
    author-pinterest: https://pinterest.com/

# Social Media Links (Links are located in hero and footer)
twitter: https://twitter.com/
facebook: https://facebook.com/
google-plus: https://plus.google.com/
instagram: https://www.instagram.com/
pinterest: https://pinterest.com/
youtube: https://www.youtube.com/

# Contact Form Settings
contact-subtitle: Contact us if you have any doubts # Title for the subscription form.

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
